app:
  name: "gofiber-skeleton"
  env: "development"
  port:
    http: 8080
    https: 8443
  path:
    cert: "./internal/assets/dev/tls/zercle-dev.crt"
    priv: "./internal/assets/dev/tls/zercle-dev.key"
    ca: "./internal/assets/dev/tls/rootCA.crt"
    log: "./log"

db:
  postgres:
    sock: "/var/run/postgresql"
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "1234"
    db_name: "postgres"
    conn:
      min: 1
      max: 2

jwt:
  # openssl ecparam -name prime256v1 -genkey -noout -out privkey.pem
  private: "./internal/assets/dev/jwt/privkey.pem"
  # openssl ec -in privkey.pem -pubout -out pubkey.pem
  public: "./internal/assets/dev/jwt/pubkey.pem"
