app:
  name: "gofiber-skeleton"
  env: "production"
  port:
    http: 8080
    https: 8443
  path:
    cert: "./internal/assets/prd/tls/zercle-prd.crt"
    priv: "./internal/assets/prd/tls/zercle-prd.key"
    ca: "./internal/assets/prd/tls/rootCA.crt"
    log: "./log"

db:
  postgres:
    sock: "/var/run/postgresql"
    host: "waste-postgres"
    port: 5432
    username: "postgres"
    password: "1234"
    db_name: "postgres"
    conn:
      min: 1
      max: 2


jwt:
  # openssl ecparam -name prime256v1 -genkey -noout -out privkey.pem
  private: "./internal/assets/prd/jwt/privkey.pem"
  # openssl ec -in privkey.pem -pubout -out pubkey.pem
  public: "./internal/assets/prd/jwt/pubkey.pem"

minio:
  endpoint: "waste-minio"
  access_key: "admin"
  secret_key: "va199uHavok4NU38DqucRZ5lflXRUeGD620YhMbwZBS0dtD8ds"
  use_ssl: false
  bucket: "waste"