basePath: /api/v1
info:
  contact:
    email: support@swagger.io
    name: API Support
  description: This is the API documentation for the Waste Management Service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Waste Management Service API
  version: "1.0"
paths:
  /auth/change-password:
    put:
      responses: {}
  /auth/login:
    post:
      responses: {}
  /auth/me:
    get:
      responses: {}
  /staff:
    get:
      responses: {}
    post:
      responses: {}
  /staff/{id}:
    delete:
      responses: {}
    get:
      responses: {}
    put:
      responses: {}
  /vehicles:
    get:
      responses: {}
    post:
      responses: {}
  /vehicles/{id}:
    delete:
      responses: {}
    get:
      responses: {}
    put:
      responses: {}
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
